name: Build actions

on:
  pull_request:
    branches: [ "main" ]
jobs:
  builds:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: make setup_app
      - name: run tests
        run: make tests
      - name: Python Cov
        uses: orgoro/coverage@v2
        with:
            coverageFile: coverage.xml
            thresholdAll: 0.5
            thresholdNew: 0.8
            thresholdModified: 0.0
            token: ${{ secrets.GITHUB_TOKEN }}